#!/usr/bin/env node

/**
 * Module dependencies.
 */
//https://www.cnblogs.com/mengff/p/9753867.html //路径path处理


process.env.NODE_ENV = 'development';//部署的时候设置成 production

var inputPara = process.argv;//输入的参数 数组，注意参数是从第3个元素开始的（index为2），第一个元素为node执行器目录地址，第二个为js执行文件地址

var fs = require('fs');
var basUtil = require('./basicUtil.js');
var path = require('path');

//提取出来的string
var all_founds = [];

console.log('inputed parameters are: '+ inputPara);

var cmd = inputPara[2];

 if(cmd == '-rpzhstr') {
    let dir = inputPara[3];
    enumerate_directory(dir, true, (err, file) => {
        findChineseString(file);
    }, (err) => {
      if(!err) {
        console.log('-----extracted ' + all_founds.length + ' strings----')
        console.log('generating localized string file...');
        let localized_str = '//This file is auto generated by xcstr.\n// author:Roen (zxllf23) https://github.com/Roen-Ro'
         let str_set = new Set(all_founds);
         str_set.forEach( (item, i) => {
          localized_str += '\n';
          localized_str += item.substring(1);
         });
         
         let desPath = dir + '/localizedstring_xcstr.strings';
         fs.writeFile(desPath,localized_str, (err) => {
          if(err)
            console.error(err.message);
          else {
            console.log('string file is generated at: ' + desPath);
          }

         });
         
      }
      else 
        console.error(err.message);
    
    });
}
else {
    console.log('available commands: ');
    console.log('-rpzhstr 查找.m .h  文件中的中文，并替换成NSLocalizedString()，所有中文字符也会输出到zh_localize.string');
}

//dir 目录路径 recursive：bool是否递归遍历子目录 handle(error,file):每遍历到一个文件就会回调 done(error):遍历完所有就会回调
function enumerate_directory (dir, recursive, handle, done) {

    fs.readdir(dir, function(err, list) {
      if (err) return done(err);
      var i = 0;
      (function next() {
        var file = list[i++];
        if (!file) return done(null);
        file = dir + '/' + file;
        fs.stat(file, function(err, stat) {
          if (stat && stat.isDirectory()) {
              if(recursive) {
                enumerate_directory(file, recursive, handle, (err) => {
                  next();
                } );
              }
              else {
                next();
              }
          } else {
            handle(null,file);
            next();
          }
        });
      })();
    });
  };

  var nslocalizedString = 'NSLocalizedString(';
  var loalizedstringMacro = 'LSTRING(';
  var prefix3 = 'imageNamed:';

  
  function findChineseString (_path) {

        if(_path.endsWith('.m') || _path.endsWith('.h') || _path.endsWith('.mm')) {
          console.log('analysis file: ' + _path);
          
          let data =  fs.readFileSync(_path);
          let info = handleFileData(data);
          if(info.matches.length > 0) {
            console.log('founds chinese strings: ' + info.matches);
            all_founds = all_founds.concat(info.matches);
          }
          if(info.modified) {
            fs.writeFileSync(_path,info.modified);
            console.log('modified: ', path.basename(_path));
          }
    }
  }

  /* 返回
  {
    matches:[]; //提取到匹配的字符 可能为空
    modified: "xxxxx" //修改后的内容 nullable
  }
  */
  function handleFileData(data) {

    let chinese_pattern =  /@"[^"]*[\u4E00-\u9FA5]+[^"\n]*?"/g;
    let text = data.toString();//将二进制的数据转换为字符串
    let founds = [];
    let retObj = {};
       
    let rewritefile = false;
      while(strs = chinese_pattern.exec(text)){
       //  console.log(strs[0] + 'lastIndex: '+chinese_pattern.lastIndex)
       let s = strs[0];
       let idx = chinese_pattern.lastIndex;
       if(stringBeforeIndexMatch(text,chinese_pattern.lastIndex-s.length,'imageNamed:'))
          continue;

        if(stringBeforeIndexMatch(text,chinese_pattern.lastIndex-s.length,nslocalizedString)) {
          //NSLocalizedString(....);只提取不做处理
        }
        else if(stringBeforeIndexMatch(text,chinese_pattern.lastIndex-s.length,loalizedstringMacro)) {
          //LSTRING(....);只提取不做处理
        }
        else {
          text = text.insertStr(idx-s.length,nslocalizedString);
          text = text.insertStr(idx+nslocalizedString.length,',nil)');
          chinese_pattern.lastIndex += (nslocalizedString.length + 5);
          rewritefile = true;
        }
        founds.push(s);
      }

      retObj.matches = founds;

      if(rewritefile) {
        retObj.modified = text;
      //  // var fname = path.basename(_path,'.m');
      //   var destPath = _path;//path.resolve(_path,'../'+fname+'_revert.m');
      //   fs.writeFile(destPath,text, (error) => {

      //   });
      }

      return retObj;
  }

function stringBeforeIndexMatch(content,index,match) {
  let len = match.length;
  if(index < len)
    return false;

  let s = content.substr(index-len,len);
  if(s == match)
    return true;
  else
    return false;

}
